### ISSUE TITLE
Usage instructions? App ID?

### ISSUE THREAD

**Issue by mankoff** [hsjunnesson/wolfram.el#1]
This seems to be the only emacs integration with Wolfram Alpha. I'm interested in using it. When I run `(wolfram-alpha)` it returns instantly with nothing but a new buffer with my query as an Org headline. There are no errors reported in `*Messages*`. I signed up for an App ID and set that in the code, but it also doesn't change anything. If I manually paste the URL it appears your code generates, with my App ID, Alpha replies,

URL: http://api.wolframalpha.com/v2/query?appid=MY_APP_ID_HERE&input="40+2"&format=image,plaintext&parsetimeout=15&scantimeout=15&podtimeout=15&formattimeout=15

```
<queryresult success="false" error="true" numpods="0" datatypes="" timedout="" timedoutpods="" timing="0.032" parsetiming="0." parsetimedout="false" recalculate="" id="" host="http://www5a.wolframalpha.com" server="55" related="" version="2.6" profile="EnterDoQuery:0.,StartWrap:0.032011">
<error>
<code>1</code>
<msg>Invalid appid</msg>
</error>
</queryresult>
```

**Comment by mankoff** [comment]
Nevermind... it just took Wolfram a few minutes to enable the API Key.

Unrelated to this... changing the URL to `format=plaintext` (remove `image`) returns results I can read, rather than links to graphics.

**Comment by hsjunnesson** [comment]
Sorry if I got your hopes up. This project is something I've played around
with and abandoned.
Thanks for regression testing it though!

**Comment by hsjunnesson** [comment]
I've updated the readme with instructions and fixed so the images are shown inline. Now it's actually useful!
