### ISSUE TITLE
[Request] Change the background and foreground colors. 

### ISSUE THREAD

**Issue by niv-l** [hsjunnesson/wolfram.el#22]
Hi, I have a dark theme, would there be any way to invert or change the background and foreground colors such that they fit the theme?

**Comment by hsjunnesson** [comment]
I wrote wolfram.el twelves years ago, and it was part a project to help me get more into Emacs. Partly as a fun toy.
I can't remember what half of this stuff does, but the API does accept both a background and foreground color. It shouldn't be too hard to send in whatever face color Emacs is using right now.
Happy to receive a pull request.

**Comment by niv-l** [comment]
hi, made a pull request implementing these and a few other features. i'd love to collaborate on this project
