### ISSUE TITLE
Doesn't load any information other than the query into buffer

### ISSUE THREAD

**Issue by geo7** [hsjunnesson/wolfram.el#5]
This is all that I get for a query 

https://vid.me/saCV

**Comment by hsjunnesson** [comment]
First, make sure that your Wolfram Alpha app id works. It should be set in your `wolfram-alpha-app-id`.
Try loading this url in your browser - insert your app id and your query:
`http://api.wolframalpha.com/v2/query?appid=<appid>&input=<query>&format=image,plaintext&parsetimeout=15&scantimeout=15&podtimeout=15&formattimeout=15`

Also, I haven't tested this using spacemacs.

**Comment by geo7** [comment]
huh - invalid ID even tho it's been setup as they ask, no worries i'll leave it for now.

**Comment by geo7** [comment]
I'll leave a note here - for some reason the API key didn't work at first, but I checked again and now it's working... so all good :)
