### ISSUE TITLE
Make the *WolframAlpha* buffer read-only

### ISSUE THREAD

**Issue by kaushalmodi** [hsjunnesson/wolfram.el#6]
Can you please set the \*WolframAlpha\* buffer in `special-mode` so that the bindings like `q` work for killing the window.

When you are populating the buffer with "pods" in `wolfram--append-pods-to-buffer`, you can let-bind `inhibiti-read-only` to `t` so that the `special-mode` buffer is writable only within that function. What do you think?

**Comment by hsjunnesson** [comment]
That's a good idea. But then I'd have to ditch the org-mode feature, since that wouldn't work in `special-mode`.

**Comment by hsjunnesson** [comment]
Fixed with 5ce62d4

**Comment by kaushalmodi** [comment]
I actually liked the org faces. You just need 2 faces for 2 heading levels.. Is that correct? If so, why not add 2 deffaces for that?

**Comment by kaushalmodi** [comment]
> But then I'd have to ditch the org-mode feature

Oh well, I liked the faces for the 2 heading levels. Those headings are the only places where we need to apply the faces.. correct?

In that case, how about using `(propertize <STRING> 'face 'some-face)`. We would need 2 `defface`s to propertize the `query` and `title` strings.. WDYT?

**Comment by kaushalmodi** [comment]
> In that case, how about using (propertize <STRING> 'face 'some-face). We would need 2 deffaces to propertize the query and title strings.. WDYT?

I just opened a PR (https://github.com/hsjunnesson/wolfram.el/pull/9) that deals with this.
